### ISSUE TITLE
Use as Rust/C library

### ISSUE THREAD

**Issue by wdecoster** [RagnarGrootKoerkamp/astar-pairwise-aligner#14]
Hi,

This looks very interesting. It appears a step is missing in the instructions to get started, probably cloning the repository?

Additionally, I was wondering if it is possible to describe some examples of how to use the library within other rust projects, rather than as a standalone aligner.

Thanks,
Wouter

**Comment by RagnarGrootKoerkamp** [comment]
Hey! Thanks for your interest ))

> This looks very interesting. It appears a step is missing in the instructions to get started, probably cloning the repository?

Right, let me explicitly add that.

> Additionally, I was wondering if it is possible to describe some examples of how to use the library within other rust projects, rather than as a standalone aligner.

Currently this is more of a research project than an end-user tool, but it's great you want to try it out. I don't expose a proper library interface currently, but it shouldn't be hard to make a small wrapper around the most important functions. I'll get back to you somewhere next week.

**Comment by RagnarGrootKoerkamp** [comment]
The plan is to make the API looks like this:
```
let params = Params {
  algorithm: AlgorithmsArgs,
  heuristic: HeuristicArgs,
}
let a = b"ACTG";
let b = b"ACGT";
let (cost, cigar) = align(a, b, params);
```
I'd simply reuse the algorithm and heuristic arguments from the command line interface [here](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/1bcf6ec698cc7b48343b1278bfb5ca7e6998e80d/src/cli/heuristic_params.rs#L39-L104), and mark those structs as `repr(C)`. (Or actually that may not be possible given the `Option`s, but I can make equivalent C types.)

I could also add the [visualizer arguments](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/1bcf6ec698cc7b48343b1278bfb5ca7e6998e80d/src/cli/visualizer.rs#L10) so that you can directly visualize things from the C-code, in case you're building with the `sdl2` flag.

Is it common to have both a Rust and C api existing next to each other? I need to figure out how to do that cleanly. Either by using separate sub-libraries `rust::` and `c::`, or by pre/suffixing all the `c` functions.

**Comment by wdecoster** [comment]
I don't know about API design, and even less about C :)

**Comment by RagnarGrootKoerkamp** [comment]
Allright, this is finally done :tada: 

The main Rust entrypoint is [`astarpa::astarpa`](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/80cd424012b27a364cd7340b0751aefacb95ea19/astarpa/src/lib.rs#L65).

I've added a C-wrapper based on [block aligner](https://github.com/Daniel-Liu-c0deb0t/block-aligner/tree/main/c) at [`astarpa-c`](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/tree/master/astarpa-c)
