### ISSUE TITLE
Versioned releases with binaries / instructions to compile to binaries?

### ISSUE THREAD

**Issue by niemasd** [RagnarGrootKoerkamp/astar-pairwise-aligner#20]
Just saw the paper (congrats!) and was super interested in incorporating A*PA into my tool for reference-guided viral multiple sequence alignment, ViralMSA:

https://github.com/niemasd/ViralMSA

I'm hesitant to incorporate it while it depends on `cargo run` commands within a cloned A*PA repo: all of the other tools I currently support have release versions and are installed as binaries, and I was hoping to keep that structure. Would it be possible for you to incorporate versioned releases, and either attach binaries to the versioned releases or have instructions to compile to a binary that can be installed (e.g. globally in a Docker image)?

**Comment by RagnarGrootKoerkamp** [comment]
Installing rust binaries as end-user is pretty staightforward.

With cargo and rust-nightly installed, you can do
```
cargo install --git https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner pa-bin
```
This downloads the repo and all dependencies and builds things, and outputs a binary to `~/.local/share/cargo/bin/pa-bin`, which you can then include in the release.

Or you can do `cargo build --release` in a cloned repo and copy the binary from the `target/release/pa-bin`.

I'll add this to the readme.

---

Re. versioning, I am slightly hesistant to introduce versions as this increases the maintenance burden a bit. But probably it's useful to at least make some explicit tags to know which version of the code people are using. I'll consider it.

---

I did notice there is currently some build issue due to changes in unstable Rust. Should be fixed in a bit.

**Comment by niemasd** [comment]
Wow, awesome, thank you! Yes, versioning would be nice for record-keeping, but no worries if it doesn't align with what you're aiming for! Worst case scenario, folks can document the version of the code they're using via commit or pull date. The updated instructions should satisfy my use case. Thanks!

**Comment by RagnarGrootKoerkamp** [comment]
I did realize that having `pa-bin` as default binary name is a bit unfortune; just `astarpa` would be nicer.
The binary has more dependencies than the core `astarpa` crate, so I prefer separating them.
Maybe I'll restructure the `pa-bin` crate to still produce a binary called `astarpa` anyway. That could then later be extended to an `astarpa2` binary.
